// Generated by `npx shadcn@latest add table`, then customized. Diverges from a
// pristine registry pull in four ways — reapply these after any regeneration:
//
// 1. `TableHead` is 11px/leading-4 and `text-muted-foreground` — headers stay
//    muted grey, and sorting is signalled by an arrow icon, never by colour.
// 2. `TableCell` is `text-base text-foreground`.
// 3. Zebra striping is an opt-in `striped` prop on `TableBody`, NOT always-on.
//    It used to be hardcoded here; default is now off, so row separation comes
//    from `border-b` on `TableRow` instead.
// 4. Row hover/selection use `bg-highlight`, not `bg-muted` (DESIGN.md §2.3's
//    highlight role) — `bg-muted` stays reserved for zebra striping.

import * as React from "react";

import { cn } from "@framework/lib/shadcn/shadcn-utils";

function Table({ className, ...props }: React.ComponentProps<"table">) {
  return (
    <div
      data-slot="table-container"
      className="relative w-full overflow-x-auto"
    >
      <table
        data-slot="table"
        className={cn("w-full caption-bottom text-sm", className)}
        {...props}
      />
    </div>
  );
}

function TableHeader({ className, ...props }: React.ComponentProps<"thead">) {
  return (
    <thead
      data-slot="table-header"
      className={cn("[&_tr]:border-b [&_tr]:border-border", className)}
      {...props}
    />
  );
}

function TableBody({
  className,
  striped,
  ...props
}: React.ComponentProps<"tbody"> & {
  /** Alternating row fill. Off by default — opt in per table. */
  striped?: boolean;
}) {
  return (
    <tbody
      data-slot="table-body"
      className={cn(
        "[&_tr:last-child]:border-0",
        // Solid `bg-muted`, not `bg-muted/60`. --muted is 0 0% 97%, so at 60%
        // alpha over a white card the band lands around 250/255 — present in the
        // DOM but invisible on screen. Solid gives 247/255, which reads as a
        // band without competing with the row borders.
        striped && "[&_tr:nth-child(even)]:bg-muted",
        className,
      )}
      {...props}
    />
  );
}

function TableFooter({ className, ...props }: React.ComponentProps<"tfoot">) {
  return (
    <tfoot
      data-slot="table-footer"
      className={cn(
        "border-t bg-muted/50 font-medium [&>tr]:last:border-b-0",
        className,
      )}
      {...props}
    />
  );
}

function TableRow({ className, ...props }: React.ComponentProps<"tr">) {
  return (
    <tr
      data-slot="table-row"
      className={cn(
        "border-b border-border transition-colors hover:bg-highlight/50 has-aria-expanded:bg-highlight/50 data-[state=selected]:bg-highlight",
        className,
      )}
      {...props}
    />
  );
}

function TableHead({ className, ...props }: React.ComponentProps<"th">) {
  return (
    <th
      data-slot="table-head"
      className={cn(
        "h-10 px-2 text-left align-middle text-label-sm font-medium whitespace-nowrap text-muted-foreground [&:has([role=checkbox])]:pr-0",
        className,
      )}
      {...props}
    />
  );
}

function TableCell({ className, ...props }: React.ComponentProps<"td">) {
  return (
    <td
      data-slot="table-cell"
      className={cn(
        "p-2 align-middle text-base text-foreground whitespace-nowrap [&:has([role=checkbox])]:pr-0",
        className,
      )}
      {...props}
    />
  );
}

function TableCaption({
  className,
  ...props
}: React.ComponentProps<"caption">) {
  return (
    <caption
      data-slot="table-caption"
      className={cn("mt-4 text-sm text-muted-foreground", className)}
      {...props}
    />
  );
}

export {
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableHead,
  TableRow,
  TableCell,
  TableCaption,
};
