/**
 * Sample: Confirmation Page Detailed — Confirmation Page Simple plus a summary of what was
 * submitted.
 *
 * Same template, same holes, same `ConfirmationPanel`; the delta is that the panel's body carries
 * an `InfoTable` and a couple of follow-on blocks. That is why the registry records it as a
 * `variantOf` the simple page rather than a peer entry.
 *
 * **The rows below are an illustration, not a default to copy.** What a real confirmation should
 * echo back is a per-page decision, and it is deliberately not only the submitted fields — the
 * reference id, the status and the timestamp here are all generated by the server, and they are
 * usually the rows the reader actually came for. The implementing agent proposes a set and
 * confirms it; see `.claude/rules/components-rules.md` § Confirmation pages.
 *
 * Values wrap rather than truncate, at every width — a summary whose job is to confirm what was
 * recorded must not hide half of it behind an ellipsis. See `InfoTable`.
 *
 * Inline mock content only — previews must render on a fresh clone with no .env.
 */

import { PiInfo } from "react-icons/pi";

import { SingleCardTemplate } from "@framework/templates/SingleCardTemplate";
import { Button } from "@framework/components/ui/button";
import { Badge } from "@framework/components/ui/badge";
import { ConfirmationPanel } from "@framework/components/ui/ConfirmationPanel";
import { InfoTable } from "@framework/components/ui/InfoTable";

/** Server-generated rows sit alongside submitted ones — see the note in the header comment. */
const SUMMARY = [
  { label: "Visit ID", value: "TC-20260825-474" },
  { label: "Guest", value: "Business Woman" },
  { label: "Company", value: "Business Company Pte Ltd" },
  { label: "Host", value: "Ivan Yanitra" },
  { label: "Entry", value: "25 Aug 2026, 5:32 pm SGT" },
  {
    label: "Status",
    value: <Badge variant="success">Active</Badge>,
  },
];

const DECLARED_ITEMS = [{ label: "Item 1", name: "iPad mini", kind: "Tablet" }];

export const ConfirmationPageDetailed = () => {
  return (
    <SingleCardTemplate
      title="Visitor registration"
      subtitle="Reception check-in"
      width="narrow"
    >
      <ConfirmationPanel
        title="Registration completed"
        description="Please wait for your host at the designated reception area. Guests must remain accompanied by their host while on company premises."
        actions={<Button variant="outline">Done</Button>}
      >
        <InfoTable rows={SUMMARY} />

        {/* A repeated block below the table: the same shape a page would use for line items,
            attachments or approvers. It lives in `children`, which is what the panel's body slot
            is for — the panel itself knows nothing about visits. */}
        <section className="space-y-2">
          <h3 className="text-sm font-medium text-foreground">
            Declared items ({DECLARED_ITEMS.length})
          </h3>
          <ul className="space-y-2">
            {DECLARED_ITEMS.map((item) => (
              <li
                key={item.label}
                className="flex items-start justify-between gap-4 rounded-sm border border-border p-3"
              >
                <div className="min-w-0">
                  <p className="text-xs font-semibold tracking-wide text-muted-foreground uppercase">
                    {item.label}
                  </p>
                  <p className="text-sm text-foreground">{item.name}</p>
                </div>
                <Badge variant="outline">{item.kind}</Badge>
              </li>
            ))}
          </ul>
        </section>

        {/* Standing instruction rather than a status, so it is a muted panel and not an Alert —
            DESIGN.md §6 keeps Alerts for states that changed. */}
        <p className="flex items-start gap-2 rounded-sm bg-muted/40 p-3 text-xs text-muted-foreground">
          <PiInfo className="mt-0.5 size-4 shrink-0" />
          <span>
            Please make sure your host checks out for you once your visit has
            concluded.
          </span>
        </p>
      </ConfirmationPanel>
    </SingleCardTemplate>
  );
};
