#!/usr/bin/env node
// Regenerates platform/framework.lock — a SHA-256 per file classified `framework` or
// `materialized` in platform/framework.json. This is what `framework:verify` hash-checks
// against in a role: "consumer" repo (Gate B — does the vendored copy still match what it was
// pinned to).
//
// Run this before tagging a framework release (`framework:publish`, once phase 4 builds it) — it
// is a deliberate, separate step from `framework:verify`, not something verify does implicitly,
// because in role: "source" (this repo, mid-development) framework files are SUPPOSED to keep
// changing between locks.
//
// Run: npm run framework:lock

import { readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import path from "node:path";
import {
  HASH_CHECKED_CATEGORIES,
  loadManifest,
  getCategories,
  classify,
  resolveRole,
  hashContent,
} from "./framework-lib.mjs";

const root = process.cwd();
const OUT = path.join(root, "platform/framework.lock");

// REFUSED in a portal, before writing anything. Re-pinning there blesses whatever is currently on
// disk — including the exact local edit to a framework file that Gate B exists to catch — so a
// single well-meaning `framework:lock` silently disarms the boundary for every later check. This
// used to be a note printed AFTER the lock had already been rewritten, which is the one ordering
// that cannot help. Same shape as framework:publish's role guard and framework:apply's --adopt
// guard: the commands whose misuse breaks the model all refuse rather than warn.
const { role } = resolveRole(root);
if (role !== "source") {
  console.error(
    [
      `framework:lock — package.json's framework.role is "${role}", not "source". Refusing.`,
      "",
      "Re-pinning the lock here would bless whatever is currently on disk, including any local",
      "edit to a framework file that `framework:verify` would otherwise have caught — so running",
      "it turns Gate B off instead of reporting the problem.",
      "",
      "If verify is complaining about a framework file in this portal, the two ways forward are:",
      "",
      "    npm run framework:reset      discard the local edit (uncommitted only)",
      "    (or) upstream the change in the framework repo, release it, then framework:update",
      "",
      "Locking is a framework-maintainer action, taken in the framework's own repo.",
    ].join("\n"),
  );
  process.exit(1);
}

const manifest = loadManifest(root);
if (!manifest) {
  console.error(
    "framework:lock — platform/framework.json not found or not valid JSON.",
  );
  process.exit(1);
}

const categories = getCategories(manifest);

let tracked;
try {
  tracked = execFileSync("git", ["ls-files"], { cwd: root, encoding: "utf8" })
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean);
} catch {
  console.error("framework:lock — `git ls-files` failed; is this a git repo?");
  process.exit(1);
}

// The lock file is itself under platform/** (classified "framework"), but it can't hash itself —
// its own content changes the moment a new hash is appended to it, which would make any hash it
// held of its own prior content immediately wrong. Excluded explicitly, not by category, so this
// stays correct even if platform/framework.lock's location ever changes.
const SELF = "platform/framework.lock";

const files = {};
let count = 0;
for (const file of tracked) {
  if (file === SELF) continue;
  const category = classify(categories, file);
  if (!category || !HASH_CHECKED_CATEGORIES.has(category.name)) continue;
  const content = readFileSync(path.join(root, file), "utf8");
  files[file] = hashContent(content);
  count++;
}

// Sorted keys — a stable, minimal diff when only a handful of files actually changed, instead of
// the whole file reordering because Set/git-ls-files iteration order shifted.
const sortedFiles = Object.fromEntries(
  Object.keys(files)
    .sort()
    .map((k) => [k, files[k]]),
);

const lock = {
  $comment: [
    "GENERATED by `npm run framework:lock` — do not hand-edit.",
    "",
    "SHA-256 of every file classified `framework` or `materialized` in platform/framework.json,",
    "as of the last time this was regenerated. `npm run framework:verify` hash-checks against",
    'this file, but ONLY in role: "consumer" — see that script\'s own comment for why role:',
    '"source" (this repo, mid-development) skips it entirely.',
    "",
    "Regenerate with `npm run framework:lock` after any framework change, before tagging a",
    "release. Two devs regenerating this at once is a one-file conflict; resolve by re-running",
    "framework:lock after the merge, same recipe as the other generated files in this repo.",
  ],
  algorithm: "sha256",
  files: sortedFiles,
};

writeFileSync(OUT, JSON.stringify(lock, null, 2) + "\n");
console.log(
  `framework:lock — wrote ${count} file hash(es) to platform/framework.lock`,
);
